### ISSUE TITLE
Add support for user-agent

### ISSUE THREAD

**Issue by crak3rjack** [Axel-Erfurt/ARD-Livestreams-for-Roku-Express#2]
Hi could it possible to add support for user-agent and thanks!
    Title: ""
    streamFormat: "hls"
    Logo: "https://"
    Stream: "https://"
    UserAgent: "http-user-agent=""

**Comment by Axel-Erfurt** [comment]
I don't know, maybe you can ask the roku devs
https://github.com/rokudev/multi-live-channel
